---
- hosts: all
  become: yes
  vars:
    - OS: xUbuntu_20.04
    - VERSION: 1.22
  tasks: 
    - name: install curl 
      become: yes
      apt: 
        name: curl 
        state: present
    - name: install apt-transport-https
      become: yes  
      apt: 
        name: apt-transport-https 
        state: present   
    - name: adding kubernetics key 
      become: yes
      apt_key: 
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
    - name: adding source list in 
      become: yes
      shell: echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
    - name: Update cache
      become: yes
      apt: update_cache=yes
    - name: Install packages
      become: yes
      shell: |
        apt -y install vim git curl wget kubelet kubeadm kubectl
        apt-mark hold kubelet kubeadm kubectl
        sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
        swapoff -a
        modprobe overlay
        modprobe br_netfilter 
        echo "net.bridge.bridge-nf-call-ip6tables = 1" >> /etc/sysctl.d/kubernetes.conf 
        echo "net.bridge.bridge-nf-call-iptables = 1" >> /etc/sysctl.d/kubernetes.conf 
        echo "net.ipv4.ip_forward = 1"  >> /etc/sysctl.d/kubernetes.conf
        sudo sysctl --system
    - name: Install CRIO
      become: yes
      shell: |
        touch /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
        echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{OS}}/ /" >> /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
        touch /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:{{VERSION}}.list
        echo "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{VERSION}}/{{OS}}/ /" >> /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:{{VERSION}}.list
        curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{OS}}/Release.key |  apt-key --keyring /etc/apt/trusted.gpg.d/libcontainers.gpg add -
        curl -L https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{VERSION}}/{{OS}}/Release.key |  apt-key --keyring /etc/apt/trusted.gpg.d/libcontainers-cri-o.gpg add -
    - name: Update cache
      become: yes
      apt: update_cache=yes
    - name: install cri-o cri-o-runc 
      become: yes
      apt: 
        name: cri-o 
        state: present
    - name: install cri-o-runc 
      become: yes
      apt: 
        name: cri-o-runc 
        state: present  
    - name: Install CRIO
      become: yes
      shell: |
         systemctl daemon-reload
         systemctl restart crio
         systemctl enable crio
         systemctl status crio  
